package main

import (
	"os"
	"testing"
)

func TestPreambleCommandIgnoresArgv0(t *testing.T) {
	for _, argv0 := range []string{
		"goku",
		"/home/me/go/bin/goku",
		"/Users/me/Library/Caches/go-build/05/0515-d/goku",
	} {
		t.Run(argv0, func(t *testing.T) {
			orig := os.Args
			t.Cleanup(func() { os.Args = orig })
			os.Args = []string{argv0, "iface", "KV", "-m", "KVMock", "-o", "kv_interface.go"}

			want := "// Code generated by goku; DO NOT EDIT\n" +
				"// Version: " + version + "\n" +
				"// Command: goku iface KV -m KVMock -o kv_interface.go\n"
			if got := preamble(); got != want {
				t.Errorf("preamble() =\n%s\nwant\n%s", got, want)
			}
		})
	}
}
